# @package _global_

defaults:
  - _self_
  - generator: wavehax.v2
  - discriminator: univnet_mssbcqt
  - train: wavehax.ryu
  - data: jvs

hydra:
  run:
    dir: ./
  output_subdir: null

out_dir: logs # Directory to output training results.
seed: 0 # Random seed.
