_target_: wavehax.generators.ComplexWavehaxGenerator
in_channels: 100
channels: 16
mult_channels: 2
kernel_size: 7
num_blocks: 8
n_fft: 480
hop_length: 240
sample_rate: 24000
prior_type: "pcph"
drop_prob: 0.0
init_weights: false
